#!/bin/bash

#export NET_XMPP2_TEST="test1_netxm2@ejabberd.ta-sa.org/x:lolfe123"
#export NET_XMPP2_TEST_MUC="conference.ejabberd.ta-sa.org"
#export NET_XMPP2_TEST_DEBUG=1
export ANYEVENT_XMPP_TEST_COMPONENT="ejabberd.test:xmpp-component=5000:test.ejabberd.test:secret123"
export ANYEVENT_XMPP_TEST_CLIENT="test_1@ejabberd.test:test_2@ejabberd.test:lolfe123"
